name: Integration

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-node@v4.2.0
      - name: Install dependecies
        run: npm install
      - name: Build app
        run: npm run build
  unit-tests:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4.2.2
        - uses: actions/setup-node@v4.2.0
        - name: Install dependecies
          run: npm install
        - name: Run unit tests
          run: npm run test